version: "3.7"

services:
    express: 
        container_name: ClashRoyale-backend
        image: backend:dev
        ports:
        - 3001:3001
        environment:
        - CHOKIDAR_USEPOLLING=true
        depends_on:
        - redis

    redis:
        container_name: ClashRoyale-redis
        image: redis
        ports:
        - 6379:6379
        environment:
        - CHOKIDAR_USEPOLLING=true
