GET http://localhost:3001/api/v1/clashroyale/cards

###
GET http://localhost:3001/api/v1/clashroyale/cards/607a6ec827b4b0477bef62c0

###
POST http://localhost:3001/api/v1/clashroyale/cards/new
Content-Type: application/json

{
    "id": 4,
    "img": "https://i.pinimg.com/originals/dc/0f/63/dc0f63a45e84b4c9c7fd3ae74440824e.png",
    "nombre": "Bruja Nocturna",
    "calidad": "Legendaria",
    "tipoCarta": "Tropa",
    "vida": 3000,
    "danio": 192,
    "velocidad": "Media"
}

###
DELETE http://localhost:3001/api/v1/clashroyale/cards/607a6ec827b4b0477bef62c0

### 
PATCH http://localhost:3001/api/v1/clashroyale/cards/607a6ec827b4b0477bef62c0
Content-Type: application/json

{
    "id": 4,
    "img": "https://i.pinimg.com/originals/dc/0f/63/dc0f63a45e84b4c9c7fd3ae74440824e.png",
    "nombre": "Bruja Nocturno",
    "calidad": "Legendaria",
    "tipoCarta": "Tropa",
    "vida": 3000,
    "danio": 192,
    "velocidad": "Media"
}